import { NgModule } from '@angular/core';
import {
  MatCardModule,
  MatToolbarModule,
  MatInputModule,
  MatDialogModule,
  MatButtonModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatMenuModule,
  MatGridListModule,
  MatTabsModule,
  MatListModule,
  MatSelectModule,
  MatRadioModule,
  MatTableModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatButtonToggleModule,
  MatPaginatorModule,
  MatSortModule,
  MatFormFieldModule,
  MatProgressBarModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatTooltipModule,
  MatSliderModule,
} from '@angular/material';
import { MatMomentDateModule } from '@angular/material-moment-adapter';

@NgModule({
  imports: [
    MatCardModule,
    MatToolbarModule,
    MatInputModule,
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatMenuModule,
    MatGridListModule,
    MatTabsModule,
    MatListModule,
    MatSelectModule,
    MatRadioModule,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatSortModule,
    MatFormFieldModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatMomentDateModule,
    MatTooltipModule,
    MatSliderModule
  ],
  exports: [
    MatCardModule,
    MatToolbarModule,
    MatInputModule,
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatMenuModule,
    MatGridListModule,
    MatTabsModule,
    MatListModule,
    MatSelectModule,
    MatRadioModule,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatSortModule,
    MatFormFieldModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatMomentDateModule,
    MatTooltipModule,
    MatSliderModule

  ]
})
export class GpMaterialModule { }
